### ISSUE TITLE
Proposal: License

### ISSUE THREAD

**Issue by badsgahhl** [andreas-mausch/csgo-skinscreenshot#16]
Hello,

just a small thing, because I saw it yesterday during my code commits.

Maybe you want to provide a License for the code here on GitHub? Currently there is none.

Other CS Tools like PTaH, Source mod etc are licensed under GPL 3, so I would propose to apply such license or MIT for example to the repository.

What are your thoughts on this? The CS community mostly relies on such open software.

**Comment by andreas-mausch** [comment]
Sure, most of my stuff is under MIT. I will check the compatibility and add a license. Thanks for the hint.

**Comment by andreas-mausch** [comment]
Added MIT License
