### ISSUE TITLE
Can I get a screenshot without open the game?

### ISSUE THREAD

**Issue by OraCheung** [andreas-mausch/csgo-skinscreenshot#2]
Can I get a screenshot without open the game?
Just use inspect link like "steam://rungame/730/76561202255233023/+csgo_econ_action_preview%20S76561198064533415A14054575206D4821822524690412075"
It would like: https://metjm.net/csgo/

**Comment by andreas-mausch** [comment]
The idea was to have a server running (which has to run the game) which you can call from clients (which don't have to run it).
So at least one computer has to run the game, sorry.

I believe metjm wasn't a thing when I started this.
